name: Docker Image CI

on:
  push:
    tags: [ v*, 1.* ]
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the Docker images
        run: |
          cd docker-tools
          refName=${{ github.ref }}
          refName=$(echo $refName | cut -d / -f 3)
          docker build -t utnetlab/term -t utnetlab/term:$refName -f term2.Dockerfile .
          docker build -t utnetlab/gui -t utnetlab/gui:$refName -f gui2.web.Dockerfile .
      - name: Compress the Docker images
        run: |
          docker save utnetlab/term | xz -3 > utnetlab_term.tar.xz
          docker save utnetlab/gui  | xz -3 > utnetlab_gui.tar.xz
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     draft: false
      #     prerelease: false
      # output: ${{ steps.create_release.outputs.upload_url }}
      - name: Upload Release Asset (term)
        id: upload-release-asset-term
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/UT-Network-Lab/TCP-IP-Laboratory/releases/1/assets{?name,label}
          asset_path: ./utnetlab_term.tar.xz
          asset_name: utnetlab_term.tar.xz
          asset_content_type: application/x-xzip
      - name: Upload Release Asset (gui)
        id: upload-release-asset-gui
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/UT-Network-Lab/TCP-IP-Laboratory/releases/1/assets{?name,label}
          asset_path: ./utnetlab_gui.tar.xz
          asset_name: utnetlab_gui.tar.xz
          asset_content_type: application/x-xzip

