name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        sudo apt install build-essential
        cd docker-tools
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
