name: Build resource CI

on:
  push:
    tags: [ v*, 1.* ]
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # - name: Get Latest Release
      #   id: get_release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     upload_url=$(curl https://api.github.com/repos/UT-Network-Lab/TCP-IP-Laboratory/releases/latest | grep upload_url | cut -d'"' -f4)
      #     echo "::set-output name=upload_url::$upload_url"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Build the Figures
        run: |
          cd Figures
          bash ./build-gns3p.sh
          zip ../Figures.zip *.gns3p
      - name: Upload Release Asset (Figures)
        id: upload-release-asset-figures
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Figures.zip
          asset_name: Figures.zip
          asset_content_type: application/zip
      - name: Build the Latex
        run: |
          docker run --rm --user="$(id -u):$(id -g)" -v "$PWD":"/repo" -w "/repo" dockershelf/latex:full  /bin/sh -c "latexmk -pdf -interaction=nonstopmode -cd **/*.tex"
          zip Documents.zip [0-9]**/*.pdf
      - name: Upload Release Asset (Documents)
        id: upload-release-asset-documents
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Documents.zip
          asset_name: Documents.zip
          asset_content_type: application/zip
      - name: Build and Compress the Docker images (term)
        run: |
          cd docker-tools
          refName=${{ github.ref }}
          refName=$(echo $refName | cut -d / -f 3)
          docker build -t utnetlab/term -t utnetlab/term:$refName -f term2.Dockerfile .
          docker save utnetlab/term | xz -5 > ../utnetlab_term.tar.xz
      - name: Upload Release Asset (term)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./utnetlab_term.tar.xz
          asset_name: utnetlab_term.tar.xz
          asset_content_type: application/x-xzip
      - name: Build and Compress the Docker images (gui)
        run: |
          cd docker-tools
          refName=${{ github.ref }}
          refName=$(echo $refName | cut -d / -f 3)
          docker build -t utnetlab/gui -t utnetlab/gui:$refName -f gui2.web.Dockerfile .
          docker save utnetlab/gui  | xz -5 > ../utnetlab_gui.tar.xz
      - name: Upload Release Asset (gui)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./utnetlab_gui.tar.xz
          asset_name: utnetlab_gui.tar.xz
          asset_content_type: application/x-xzip
      - name: Publish to GitHub Package
        run: |
          refName=${{ github.ref }}
          refName=$(echo $refName | cut -d / -f 3)
          cat ~/GH_TOKEN.txt | docker login docker.pkg.github.com -u amirhakh --password-stdin
          docker tag utnetlab/term docker.pkg.github.com/ut-network-lab/tcp-ip-laboratory/utnetlab/term
          docker tag utnetlab/term docker.pkg.github.com/ut-network-lab/tcp-ip-laboratory/utnetlab/term:$refName
          docker tag utnetlab/gui docker.pkg.github.com/ut-network-lab/tcp-ip-laboratory/utnetlab/gui
          docker tag utnetlab/gui docker.pkg.github.com/ut-network-lab/tcp-ip-laboratory/utnetlab/gui:$refName
          docker push docker.pkg.github.com/ut-network-lab/tcp-ip-laboratory/term docker.pkg.github.com/ut-network-lab/tcp-ip-laboratory/term:$refName
          docker push docker.pkg.github.com/ut-network-lab/tcp-ip-laboratory/gui docker.pkg.github.com/ut-network-lab/tcp-ip-laboratory/gui:$refName

